Docker: PyNaCl needs libsodium-dev round two
After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5/3.6
----

### Description
Based on PR #1578. The libsodium-dev, musl-dev and libffi-dev is required for discord.py so I've removed them from the virtual .build-deps, so they won't be purged.
This pr would be the fix for the following error message:
```
[ERROR:bot] Unknown error attempting to connect to voice
Traceback (most recent call last):
  File "/usr/src/musicbot/musicbot/bot.py", line 456, in get_voice_client
    vc = await self.join_voice_channel(channel)
  File "/usr/src/musicbot/musicbot/bot.py", line 416, in join_voice_channel
    voice = discord.VoiceClient(**kwargs)
  File "/usr/lib/python3.6/site-packages/discord/voice_client.py", line 217, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice
```